"use client";

import type { Metadata } from "next";
import "./globals.css";
import { auth } from "@/lib/firebase.config";
import { useRouter } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  auth.onAuthStateChanged(function (user) {
    if (user) {
      console.log("This is the user: ", user);
      router.push("/auth/home");
    } else {
      console.log("There is no logged in user");
      router.replace("/");
    }
  });
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
